---
journal: "Departamento de Estatística"

# Use draft to submit a paper
classoption: "draft"
# A title should be specific, informative, and brief. Use
# abbreviations only if they are defined in the abstract. Titles that
# start with general keywords then specific terms are optimized in
# searches
title: "Vendas de jogos de videogames"
# First name or initial followed by last name
# Authors are individuals who have significantly contributed to the
# research and preparation of the article. Group authors are allowed, if
# each author in the group is separately identified in an appendix.
# Additional author notes should be indicated with
authors:
  - name: Guilherme da Rocha Cunha
    affil: 1
  - name: Gabriel Maurício Chagas Silva
    affil: 1
  - name: Gustavo Almeida Valentim
    affil: 1
affiliations:
  - number: 1
    name: "Universidade de Brasília, CIC - Depto de Ciências da Computação"

keypoints:  
  - "Exercitar os conhecimentos adquiridos ao longo do curso \"EST0001 - COMPUTAÇÃO EM ESTATÍSTICA 1\"."
  
abstract: "Este documento consiste no relatório do trabalho final da disciplina \"EST0001 - COMPUTAÇÃO EM ESTATÍSTICA 1\". Nele se encontra o desenvolvimento da análise do conjunto de dados escolhido pelo grupo utilizando as ferramentas provenientes do R Markdown e das bibliotecas ggplot, tidyverse e dentre outras."

output: 
    rticles::agu_article
bibliography: agutest.bib
header-includes: 
      - \usepackage{soulutf8}  # For UTF8 chars in TrackChanges
# AGU recommends using the trackchanges LaTeX package in the edition process
# which is available from this link:
# https://publications.agu.org/files/2019/02/January-14-2019-latex-templates.zip
---

```{r echo=FALSE}
# Some recommended settings. 
knitr::opts_chunk$set(
  echo = FALSE,
  fig.pos = 'h',
  out.extra = "",   # To force the use of figure enviroment
  fig.cap = "Please caption every figure"
)
```

```{r keypoints_check, echo=FALSE, results='asis', eval = TRUE}
# This chunk adds a warning if any keypoint is longer than 100 characters. 
# To disable it, you can remove it or set eval to FALSE.
if (any(nchar(rmarkdown::metadata$keypoints) > 100)) {
  cat("\\textcolor{red}{\\textbf{Warning}: keypoint(s)", 
      knitr::combine_words(which(nchar(rmarkdown::metadata$keypoints) > 100)), 
      "longer than 100 characters.}")
}
```

# Introdução e Objetivos
<!---texto--->

# Metodologia
<!---texto--->


# Análise de Dados
<!---texto--->


# Conclusão
<!---texto--->

