---
title: "Dados Trabalho Final"
author: "Guilherme da Rocha Cunha - 221030007"
output: 
  pdf_document:
    latex_engine: xelatex
---

É importante salientar que as conclusões tomadas levam em consideração o dataset, e que este possui dados apenas até o ano de 2016.


```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(patchwork)
library(hrbrthemes)

tabela = read.csv("vgsales.csv") %>% tibble()
tabela = tabela %>%
  select(-c("NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"))
tabela

```

\newpage

```{r, warning=FALSE, message=FALSE}
popularidade_anos = tabela %>%
  group_by(Year) %>%
  summarise(n = n(),
            Total_Sales = sum(Global_Sales))

popularidade_anos %>%
  ggplot(aes(x=Year)) +
  geom_line(aes(y=n), color = "royalblue") +
  geom_line(aes(y=Total_Sales), color = "lightgreen") +
  scale_y_continuous(
    name = "Número de jogos",
    sec.axis = sec_axis(~.*1,name="Vendas Globalmente (em milhões)")) +
  scale_color_manual(
    name = "Legenda"
  ) +
  labs(
    title = "Popularidade dos jogos no decorrer dos anos",
    x = "Anos"
  )

```

\newpage

```{r,warning=FALSE, message=FALSE}
popularidade_generos = tabela %>%
  group_by(Year, Genre) %>%
  summarise(Total_Sales = sum(Global_Sales))

popularidade_generos

popularidade_generos %>%
  ggplot(aes(x = Year, y = Total_Sales, fill = Genre)) +
  geom_area() +
  scale_fill_brewer(palette = "Paired") +
  labs(
    title = "Popularidade dos gêneros no decorrer dos anos",
    x = "Anos",
    y= "Vendas globais (em milhões)",
    fill = "Gêneros"
  )

```

\newpage

```{r,warning=FALSE, message=FALSE}
plataformas_jogos = tabela %>%
  group_by(Platform) %>%
  summarise(n = n()) %>%
  arrange(desc(n)) %>%
  head(10)

tabela %>%
  group_by(Platform,Genre) %>%
  summarise(Global_Sales = sum(Global_Sales)) %>%
  filter(Platform %in% plataformas_jogos$Platform) %>%
  ggplot(aes(Platform,Genre,fill=Global_Sales)) +
    geom_tile() +
    scale_fill_gradient(low="lightyellow",high="darkred") + 
  labs(
    title = "Popularidade dos gêneros nas plataformas mais populares",
    x = "Plataforma",
    y = "Gênero",
    fill = "Vendas globais (em milhões)"
  )

```

\newpage

```{r,warning=FALSE, message=FALSE}
top_cem = tabela %>%
  filter(Rank <= 100) %>%
  arrange(Rank)

empresas_top_cem = top_cem %>%
  group_by(Publisher, Genre) %>%
  summarise(n = n(),
            Global_Sales = sum(Global_Sales)) %>%
  ggplot(aes(x=Publisher, y = n, fill = Genre)) +
  geom_bar(position="stack", stat="identity") + 
  scale_fill_brewer(palette = "Paired") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title = "Principais empresas do Top 100 jogos",
    y= "Número de jogos",
    fill = "Gêneros"
  )
empresas_top_cem

```

\newpage

```{r,warning=FALSE, message=FALSE}

generos_top_cem = top_cem %>%
  group_by(Genre) %>%
  summarise(n=n())
  
generos_top_cem %>%
  ggplot(aes(x="",y=n,fill=Genre)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y") + 
  scale_fill_brewer(palette="Paired") +
  theme_void() +
  labs(
    title="Proporção de gêneros no Top 100 jogos",
    fill="Gêneros"
  )
```

\newpage

```{r,warning=FALSE, message=FALSE}
library(gt)

top_cem %>% 
  filter(Rank <= 10) %>%
  rename(
    Nome = Name,
    Plataforma = Platform,
    Ano = Year,
    Gênero = Genre,
    Empresa = Publisher,
    Vendas_Globais = Global_Sales
  ) %>%
  gt() %>%
  tab_header(title=md("Top 10 jogos mais vendidos")) %>%
  tab_footnote(
    footnote="Em milhões",
    locations=cells_column_labels(columns=Vendas_Globais)
  )
  
  
```

